### PR TITLE
adding Bf file type support

### PR DESCRIPTION
**Pull request by harlequinzeg0**
adding .BF file block types

### CODE REVIEW

**Comment by amorilia** [comment]
Thanks for the patch! Just two questions:
1. I don't see anything wrong with the xml right away - however, this doesn't concern the nif format at all, or does it? If so, then wouldn't it be better to maintain the format in a separate xml file (in a separate git repository? For example, we already have a separate repository for the kfm format:
   
   https://github.com/amorilia/kfmxml
   
   In other words: is there any compelling reason to keep these definitions inside of nif.xml?
2. I guess the format could be added to pyffi so it could be edited with QSkope. How are you currently using this code to edit the files?

**Comment by harlequinzeg0** [comment]
in answer to the first question, its an animation file type modified from the KF filetype using compression so i would assume it'd fit under the nif format however if you want to add support for it as a seperate xml i'll need some help setting that up : P

2, im using this code to manually convert KF's into BFs in nifskope by copying the needed rotation data and such into the BF equivalent data blocks, then i save it as a KF file since i cant save it as a BF file. i then remove the header strings from it using a hex editor since BF files dont have a header saying its file version and block array. it'd be easier to add its own support if it had new basic values i was asking for on the forums : P

**Comment by amorilia** [comment]
Interesting method. :-)

This isn't what I would recommend an average user. For the time being, I would suggest that you maintain your own xml until we have a proper bf editor. Since, format-wise, bf has no overlap with nif, eventually this probably belongs better in its own xml.

The xml description is at this moment in process of being revised, and one of the items on the agenda is indeed to allow specification of more basic types. I'll leave this pull request open and post back here as we come closer to our goal - it may take a while though.

**Comment by harlequinzeg0** [comment]
that is fine, our modding community shall continue to keep our private copy of the xml till nifskope can better integrate the BF format :) be sure to message me when we can work on that :D

**Comment by amorilia** [comment]
Yes, of course. One feature that nifskope should have is the possibility to include "foreign" xml files - that way you don't need to remerge with nif.xml on every nifskope update. I'll have a look at adding such feature.

**Comment by harlequinzeg0** [comment]
that should hopefully be  useful

**Pull request closed without merging**
