### PR TITLE
Resolve remaining differences with the old pyffi branch.

### PR DESCRIPTION
**Pull request by amorilia**
@neomonkeus @ttl269 Ok to merge? This is (I hope...) the last bit required to have a fully functional unified nif.xml.

### CODE REVIEW

**Comment by amorilia** [comment]
Additional note: updates nifskope/niflib/pyffi that take into account all these changes are already done (will do pull requests for those when this is approved for merging):

https://github.com/amorilia/nifskope/compare/develop...feature;pyffi-bug-fixes
https://github.com/amorilia/niflib/compare/bc7597e7aed749bca8233753b948ee95308ea69e...feature/pyffi-bug-fixes
https://github.com/amorilia/pyffi/compare/dbcedeae9382d4b0d6e9f815f43ec71f55484de1...master

**Comment by ttl269** [comment]
OK. I am only able to look at changes in nif.xml concerning the nif format irself. I don't know/use Python, so I can't check anything concerning pyffi things.

**Comment by amorilia** [comment]
Of course @ttl269 I've CC'd you in because you're our top xml expert, and at this point in the process, this is just about the xml. Don't worry about pyffi/nifskope/niflib - others can worry about that in due time.

**Comment by amorilia** [comment]
For the record, @neomonkeus approved over IRC.

**Pull request merged**
