### PR TITLE
added some Skyrim materials

### PR DESCRIPTION
**Pull request by ttl269**

### CODE REVIEW

**Comment by amorilia** [comment]
Thanks! Looks generally good, but duplicate names, such as

```
SKY_HAV_MAT_UNKNOWN
```

will definitely give trouble for niflib and pyffi. Could you make them unique somehow, e.g. by replacing them with 

```
SKY_HAV_MAT_<material number>
```

?

**Comment by amorilia** [comment]
Bah github messed with the formatting of my post again - fixed...

**Comment by ttl269** [comment]
Yes, it is good idea to make them unique by add its number. I'll do it. And sorry for my forgetting that there should not be duplicate names. I'll try to remember to it when making some next nif.xml update. I have prepared one - skyrim specific "Layer" and "ColFilter" in bhkRigidBody and try to post it here.

**Comment by amorilia** [comment]
Looks great. Thanks a lot!

**Pull request merged**
