### PR TITLE
Fix havok material version check.

### PR DESCRIPTION
**Pull request by amorilia**
@ttl269 @neomonkeus Not tested yet, but this looks like the simplest solution (explanation: as bhk blocks only occur in bethesda nifs anyway, the user version check should be sufficient).

Ok to merge (pending my own testing still)?

### CODE REVIEW

**Comment by amorilia** [comment]
... side note: this proves once more we need <if> <else> blocks. :-)

**Comment by amorilia** [comment]
Has passed my own initial testing - re-running a full xml check against my full nif collection just in case.

**Comment by ttl269** [comment]
The solution with only user version check seems to be sufficient. I have only Skyrim, Oblivion and Fallout3 nif files to test and it seems ok. Don't know if nifs from latest Skyrim DLCs (have not any) has same user version number, but I hope that yes. So we can take user version >= 12 as a Skyrim nif. (…until some next game comes with same user version and different havok material numbers).
Yes, if-else blocks would be nicer :)

**Comment by amorilia** [comment]
@ttl269 Thanks for the additional testing! I've now also tested all of skyrim, fallout 3/nv, and oblivion (and about 15 other games, but none that use bhk blocks), with pyffi, confirming the fix.

This seems important enough to warrant a hotfix release for our tools - I'll be on it tomorrow.

**Pull request merged**
